---
# tasks file for kubernetes master


- name: Configure Kubernetes Repository
  shell: |
    cat <<EOF > /etc/yum.repos.d/kubernetes.repo
    [kubernetes]
    name=Kubernetes
    baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled=1
    gpgcheck=1
    repo_gpgcheck=1
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    EOF
  

- name: install kubelet
  yum:
    name: kubelet
    state: installed


- name: install kubeadm
  yum:
    name: kubeadm
    state: installed


- name: install kubectl
  yum:
    name: kubectl
    state: installed


- name: Enable kubelet service
  shell: systemctl enable kubelet

- name: Start kubelet service
  shell: systemctl start kubelet


- name: set hostname node
  hostname:
    name: master-node

- name: copy hosts.j2 file to /etc/hosts
  template: 
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'


- name: add port
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items:
    - 6443
    - 2379-2380
    - 10250
    - 10252
    - 10255
    - 10251

- name: Update iptable setting
  shell: |
    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF

- name: Update iptable setting
  shell: sysctl --system

- name: Desable SELINUX first step
  shell: sudo setenforce 0  && sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: Disable SWAP
  shell: sudo sed -i '/swap/d' /etc/fstab && sudo swapoff -a


- name: create join_message.sh file
  file:
    path: "{{ home }}/join_message.sh"
    state: touch

- name: Create Cluster with kubeadm
  shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 >> "{{ home }}/join_message.sh"
  register: join_message
  ignore_errors: yes



- name: create kube directory
  file:
    path: $HOME/.kube
    state: directory
    owner: root

- name: copy admin.conf to .kube/config
  shell: cat  /etc/kubernetes/admin.conf > $HOME/.kube/config

- name: Run cluster by regular user
  shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Set Up Pod Network
  shell: sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    





