---

# Cluster node installation
- name: Cluster master node installation with kubeadm
  hosts: master-node
  gather_facts: yes
  become: yes

  vars:
    pip_install_packages:
      - name: docker

    pip_package: python-pip

    pip_executable: pip

  pre_tasks:
   - name: install python-pip
     package: name=python-pip state=present update_cache=yes


  roles:
    - { role: geerlingguy.pip }
    - { role: geerlingguy.docker }
    - { role: KubernetesMaster }



# Cluster node installation
- name: Cluster worker node installation with kubeadm
  hosts: worker-node
  gather_facts: yes
  become: yes

  vars:
    pip_install_packages:
      - name: docker

    pip_package: python-pip

    pip_executable: pip

  pre_tasks:
   - name: install python-pip
     package: name=python-pip state=present update_cache=yes


  roles:
    - { role: geerlingguy.pip }
    - { role: geerlingguy.docker }
    - { role: KubernetesWorker }

