apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-deployment
  namespace: franck
spec:
  selector:
    matchLabels:
      app: nginx_l
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx_l
    spec:
       containers:
       - name: nginx
         image: nginx:latest
         ports:
         - containerPort: 80

